/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_steven_ndk12_NDKSimple1 */

#ifndef _Included_com_steven_ndk12_NDKSimple1
#define _Included_com_steven_ndk12_NDKSimple1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_steven_ndk12_NDKSimple1
 * Method:    changeName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_steven_ndk12_NDKSimple1_changeName
  (JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_com_steven_ndk12_NDKSimple1_changeAge
(JNIEnv *, jclass);



#ifdef __cplusplus
}
#endif
#endif
