/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h" //""引入自己的头文件 
/* Header for class com_steven_ndk12_NDKSimple */

//用来打一个标记，c在编译的时候会把头文件copy引入的地方，不管是重复引用还是相互引用


#ifndef _Included_com_steven_ndk12_NDKSimple
#define _Included_com_steven_ndk12_NDKSimple
#ifdef __cplusplus
//加上extern "C"后，会指示编译器这部分代码按C语言的进行编译，而不是C++的,因为c里面不允许函数的重载，而c++支持
extern "C" {
#endif
/*
 * Class:     com_steven_ndk12_NDKSimple
 * Method:    getSingnturePassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_steven_ndk12_NDKSimple_getSingnturePassword
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
