/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_steven_ndk13_Simple1 */

#ifndef _Included_com_steven_ndk13_Simple1
#define _Included_com_steven_ndk13_Simple1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_steven_ndk13_Simple1
 * Method:    callMethodCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_steven_ndk13_Simple1_callMethodCallback
  (JNIEnv *, jclass);



JNIEXPORT jobject JNICALL Java_com_steven_ndk13_Simple1_createPoint
(JNIEnv *, jclass);



#ifdef __cplusplus
}
#endif
#endif
